wsgi_app = "main:app"
reload = False
print_config = False
accesslog = '-'
access_log_format = '%(t)s %(M)s %(U)s %(r)s'
errorlog = '-'
loglevel = 'info'
limit_request_line = 8190
limit_request_fields = 1000
limit_request_field_size = 15000
bind = '0.0.0.0:8000'
workers = 1
worker_class = 'uvicorn.workers.UvicornWorker'
threads = 1
worker_connections = 1000
max_requests = 0
timeout = 0
proc_name = 'meeting_room_control'
