# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.asr_backend import main_pb2 as proto_dot_asr__backend_dot_main__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/asr_backend/main_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AsrBackendStub(object):
    """服务定义

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AudioToText = channel.unary_unary(
                '/asr_backend.AsrBackend/AudioToText',
                request_serializer=proto_dot_asr__backend_dot_main__pb2.Request.SerializeToString,
                response_deserializer=proto_dot_asr__backend_dot_main__pb2.Response.FromString,
                _registered_method=True)


class AsrBackendServicer(object):
    """服务定义

    """

    def AudioToText(self, request, context):
        """视频内容过滤
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsrBackendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AudioToText': grpc.unary_unary_rpc_method_handler(
                    servicer.AudioToText,
                    request_deserializer=proto_dot_asr__backend_dot_main__pb2.Request.FromString,
                    response_serializer=proto_dot_asr__backend_dot_main__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asr_backend.AsrBackend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asr_backend.AsrBackend', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AsrBackend(object):
    """服务定义

    """

    @staticmethod
    def AudioToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr_backend.AsrBackend/AudioToText',
            proto_dot_asr__backend_dot_main__pb2.Request.SerializeToString,
            proto_dot_asr__backend_dot_main__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
