# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/asr_backend/main.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/asr_backend/main.proto\x12\x0b\x61sr_backend\"\x17\n\x07Request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\r\n\x0bNullRequest\"\x18\n\x08Response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32J\n\nAsrBackend\x12<\n\x0b\x41udioToText\x12\x14.asr_backend.Request\x1a\x15.asr_backend.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.asr_backend.main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=45
  _globals['_REQUEST']._serialized_end=68
  _globals['_NULLREQUEST']._serialized_start=70
  _globals['_NULLREQUEST']._serialized_end=83
  _globals['_RESPONSE']._serialized_start=85
  _globals['_RESPONSE']._serialized_end=109
  _globals['_ASRBACKEND']._serialized_start=111
  _globals['_ASRBACKEND']._serialized_end=185
# @@protoc_insertion_point(module_scope)
